### ISSUE TITLE
Function to remove vertex/edge

### ISSUE THREAD

**Issue by peroksid90** [amplab/graphx#140]
Add functions to remove simple vertex or edge.

**Comment by ankurdave** [comment]
Is [`Graph.subgraph`](http://spark.apache.org/docs/latest/api/graphx/index.html#org.apache.spark.graphx.Graph@subgraph%28%28EdgeTriplet[VD,ED]%29⇒Boolean,%28VertexId,VD%29⇒Boolean%29:Graph[VD,ED]) the operation you're looking for?

**Comment by peroksid90** [comment]
Graph.subgraph  fit for me. But i thought this was slowly  in case like this:

pseudo-code:
n=100000;
con_comp_under_attack = [];
while(n) {
          remove simple vertex from graph
          con_comp_under_attack.append( count the number of vertices on largest connected components)
          n--
}

**Comment by ankurdave** [comment]
Oh, I see. Yes, the current implementation of `subgraph` is inefficient for point removals, since it rebuilds the routing table (requiring a shuffle) and constructs new edge partitions as well.

I have a pull request (apache/spark#497) that avoids the shuffle, but it still rebuilds the edge partitions. However, we plan to add a bitmask to the edges to avoid needing to rebuild them in cases like this.

Unfortunately, the best you can currently do is to apply this pull request and continue to use `subgraph`, since there's no other way to remove vertices at the moment.

**Comment by peroksid90** [comment]
Thank you very much.
